fixes for MSVC 14.1, aka VS 2017
- move project ahead to avoid compiler tests failure
- add option BUILD_TOOL to disable dvtest
- remove CXX_FLAGS not compatible with MSVC
- add __WINDOWS__ as compiler definition because not defined
- remove (const wchar_t*)  error C2664
  tested on windows and ubuntu 16.04 (no warning)